git add Test_Game.cbp
git add .\src/Block.cpp
git add .\src/CApp.cpp
git add .\src/CApp_OnCleanup.cpp
git add .\src/CApp_OnEvent.cpp
git add .\src/CApp_OnInit.cpp
git add .\src/CApp_OnLoop.cpp
git add .\src/CApp_OnRender.cpp
git add .\src/Entity.cpp
git add Makefile.ps1
git add .\src\Timer.cpp
git add .\src\Public_functions.cpp